config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :poem_bills
  resources :poems
  resources :words
  resources :bill_words
  resources :bills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get '/' => 'home#index'
	get '/home' => 'home#index'
end

app/models/poem.rb
class Poem < ApplicationRecord
	def initialize
	end

	def self.write_poem
		@words = BillWord.all.sample(500)
		@words = Word.where(word_kid:@words.map{|m| m[:word_kid]}).reject{|m| m['word'].match(/[^a-z]/) }.map{|m| m.as_json.merge(syllables: self.syllables(m['word'])) }
		@words = @words.map{|m| m[:syllables] > 0 ? m : m.merge({syllables: 1})}
		
		randomize = Random.new

		sorted = Hash.new

		tgr = EngTagger.new

		@words.each do |hash|
			sorted[hash[:syllables]] ||= []
			sorted[hash[:syllables]] << hash
		end

		if !sorted.has_key?(1)
			sorted[1] = ['a','the','of','and']
		end

		lines = [5, 7, 5]

		output = []

		lines.each do |syllables|
			invalid = 1
			linewords = []
			while invalid
				linewords = []
				line = ''
				while syllables > 0
					temp = sorted.reject{|k,v| k > syllables}

					syls = temp.keys[randomize.rand(temp.keys.count)]
					
					wurdz = temp[syls]

					selection = wurdz[randomize.rand(wurdz.count)]
					
					line = line + ' ' + selection['word']
					linewords << selection
					
					syllables -= syls
				end

				analysis = Nokogiri::XML("<sentence>" + tgr.add_tags(line) + "</sentence>")
				if analysis.xpath('//nn') != [] and analysis.xpath('//vbz') != []
					invalid = nil
				end
			end
			output << {line: line.strip.capitalize, linewords: linewords }
		end

		output = output.map{|m| 
			{
				line: m[:line],
				linewords: m[:linewords].map{|n|
					bill_kid = BillWord.where(word_kid: n['word_kid'])
					bill_kid = bill_kid ? bill_kid.all.sample(1).first['bill_kid'] : nil
					{
						word: n['word'],
						bill: Bill.find_by(bill_kid: bill_kid ? bill_kid : 0)
					}
				}  
			}
		}

		output
	end

	def self.syllables(word)
		word.scan(/([AEIOUaeiouy]+(?!$|s$|d$))|((?<=k|v|z)[AEIOUaeiouy]+)|(ly$)|(ing$)|((?:p|b)le$)|([^AEIOUY]e(?:s|d)$)/).count
	end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:poem_kid, :text)
    end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/_form.html.erb
<%= form_for(poem) do |f| %>
  <% if poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :poem_kid %>
    <%= f.number_field :poem_kid %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poems</h1>

<table>
  <thead>
    <tr>
      <th>Poem kid</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td><%= poem.poem_kid %></td>
        <td><%= poem.text %></td>
        <td><%= link_to 'Show', poem %></td>
        <td><%= link_to 'Edit', edit_poem_path(poem) %></td>
        <td><%= link_to 'Destroy', poem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poem', new_poem_path %>

app/views/poems/new.html.erb
<h1>New Poem</h1>

<%= render 'form', poem: @poem %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poem kid:</strong>
  <%= @poem.poem_kid %>
</p>

<p>
  <strong>Text:</strong>
  <%= @poem.text %>
</p>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>