config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :poem_bills
  resources :poems
  resources :words
  resources :bill_words
  resources :bills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get '/' => 'home#index'
	get '/home' => 'home#index'
end

app/models/poem_bill.rb
class PoemBill < ApplicationRecord
end

app/controllers/poem_bills_controller.rb
class PoemBillsController < ApplicationController
  before_action :set_poem_bill, only: [:show, :edit, :update, :destroy]

  # GET /poem_bills
  # GET /poem_bills.json
  def index
    @poem_bills = PoemBill.all
  end

  # GET /poem_bills/1
  # GET /poem_bills/1.json
  def show
  end

  # GET /poem_bills/new
  def new
    @poem_bill = PoemBill.new
  end

  # GET /poem_bills/1/edit
  def edit
  end

  # POST /poem_bills
  # POST /poem_bills.json
  def create
    @poem_bill = PoemBill.new(poem_bill_params)

    respond_to do |format|
      if @poem_bill.save
        format.html { redirect_to @poem_bill, notice: 'Poem bill was successfully created.' }
        format.json { render :show, status: :created, location: @poem_bill }
      else
        format.html { render :new }
        format.json { render json: @poem_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poem_bills/1
  # PATCH/PUT /poem_bills/1.json
  def update
    respond_to do |format|
      if @poem_bill.update(poem_bill_params)
        format.html { redirect_to @poem_bill, notice: 'Poem bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem_bill }
      else
        format.html { render :edit }
        format.json { render json: @poem_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poem_bills/1
  # DELETE /poem_bills/1.json
  def destroy
    @poem_bill.destroy
    respond_to do |format|
      format.html { redirect_to poem_bills_url, notice: 'Poem bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem_bill
      @poem_bill = PoemBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_bill_params
      params.require(:poem_bill).permit(:poem_kid, :bill_kid)
    end
end

app/helpers/poem_bills_helper.rb
module PoemBillsHelper
end

app/views/poem_bills/_form.html.erb
<%= form_for(poem_bill) do |f| %>
  <% if poem_bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poem_bill.errors.count, "error") %> prohibited this poem_bill from being saved:</h2>

      <ul>
      <% poem_bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :poem_kid %>
    <%= f.number_field :poem_kid %>
  </div>

  <div class="field">
    <%= f.label :bill_kid %>
    <%= f.number_field :bill_kid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poem_bills/edit.html.erb
<h1>Editing Poem Bill</h1>

<%= render 'form', poem_bill: @poem_bill %>

<%= link_to 'Show', @poem_bill %> |
<%= link_to 'Back', poem_bills_path %>

app/views/poem_bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poem Bills</h1>

<table>
  <thead>
    <tr>
      <th>Poem kid</th>
      <th>Bill kid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poem_bills.each do |poem_bill| %>
      <tr>
        <td><%= poem_bill.poem_kid %></td>
        <td><%= poem_bill.bill_kid %></td>
        <td><%= link_to 'Show', poem_bill %></td>
        <td><%= link_to 'Edit', edit_poem_bill_path(poem_bill) %></td>
        <td><%= link_to 'Destroy', poem_bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poem Bill', new_poem_bill_path %>

app/views/poem_bills/new.html.erb
<h1>New Poem Bill</h1>

<%= render 'form', poem_bill: @poem_bill %>

<%= link_to 'Back', poem_bills_path %>

app/views/poem_bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poem kid:</strong>
  <%= @poem_bill.poem_kid %>
</p>

<p>
  <strong>Bill kid:</strong>
  <%= @poem_bill.bill_kid %>
</p>

<%= link_to 'Edit', edit_poem_bill_path(@poem_bill) %> |
<%= link_to 'Back', poem_bills_path %>